### ISSUE TITLE
v1.11.0 -- useMasterKey in beforeSave

### ISSUE THREAD

**Issue by christianpbrink** [parse-community/Parse-SDK-JS#524] opened 2017-12-04 15:54 UTC
It fails. Tells me the master key hasn't been provided. Never did this in previous versions; I've rolled back to 1.10.0 and it's working fine again.

**Comment by flovilmart** [comment] 2017-12-04 16:29
Can you provide a code example please?

**Comment by milesrichardson** [comment] 2017-12-05 11:42
@christianpbrink Are you using postgres or mongo?

The `parse-server` repo has a PR from greenkeeper with failing tests for updated `Parse-SDK-JS` on postgres: https://github.com/parse-community/parse-server/pull/4414 If you look at the errors, they are related to master key. Though I'm not familiar with these tests and those might just be warnings. But could be related.

**Comment by flovilmart** [comment] 2017-12-05 13:34
The failing test with Postgres was just a flaky test.
@christianpbrink, can you provide more details?

**Comment by christianpbrink** [comment] 2017-12-05 21:54
Sorry @flovilmart, I will try to get around to this. I've got other stuff on my plate today.

It was happening on any use of Parse.Query.find or Parse.Query.first with {useMasterKey:true} inside a .beforeSave hook.

**Comment by christianpbrink** [comment] 2017-12-05 23:00
Oh wait you mean that version of the JS SDK isn't even officially released yet? I had manually set a requirement for 1.11.0 in my project's package.json. Not sure where I got the idea that it was released.

**Comment by flovilmart** [comment] 2017-12-05 23:03
it is officially released, however, the Parse SDK dependency inside parse-server is not automatically updated as we pin all dependencies aggressively to prevent unexpected breaking changes.

If you pinned the parse SDK in your package.json, it is probable that Cloud Code would run the parse SDK from the relative node modules folder, and not the one you pinned at the top level.

You can easily check that the SDK is exposed at v1.11 by checking `Parse.setAsyncStorage` if it's undefined, you're still on the old one, if not, you're on the new one.

**Comment by christianpbrink** [comment] 2017-12-05 23:05
Hm. The problem definitely appeared as soon as I upped to 1.11.0 and vanished as soon as I reverted to 1.10.0. Of course it's possible this was due to some other change that I happened to make at the same time without noticing it.

**Comment by flovilmart** [comment] 2017-12-05 23:07
Perhaps the problem is that you're trying to use 2 versions of the Parse SDK within the same server.

**Comment by christianpbrink** [comment] 2017-12-05 23:08
Oh snap. Very possible. I will keep that possibility in mind when I revisit this. Thanks for the thought.

**Comment by flovilmart** [comment] 2017-12-05 23:31
I’ll close this one, also, 1.11 didn’t provide any change into this area. Please reopen the issue if it persists after next parse-server version is released.

**Closed by flovilmart** 2017-12-05 23:31 UTC
