### ISSUE TITLE
Parse.User.login don't work as expected

### ISSUE THREAD

**Issue by omar-bz** [parse-community/Parse-SDK-JS#490] opened 2017-10-16 10:24 UTC
Hi I'm using "parse": "^1.9.2".
the problem is present when trying to login with invalid user, it generate an error.
when using: 
`Parse.User.logIn(email,pass,{success:u=>do_some_stuff(u),error:e=>show_the_error_message(e)}) `
an error is loged to the console and the error function is fired:
![untitledscs](https://user-images.githubusercontent.com/20848841/31708253-60cb2da0-b3e6-11e7-95e9-79b3c52642cc.png)

but when using the promises:
`Parse.User.logIn(email,pass).then(u=>do_some_stuff(u)).catch(e=>show_the_error_message(e))`
it only log the error on the console and do not resolve or reject the promise.
How this is happening and to fix it.
**edit:** 

`Parse.User.logIn` instead of `Parse.logIn`

**Comment by wesliel** [comment] 2017-10-25 18:32
According to [JS SDK](http://parseplatform.org/Parse-SDK-JS/api/classes/Parse.html), Parse object doesn't have logIn method, it belongs to Parse.User. Does it work if it invokes Parse.User.logIn() instead?

**Comment by natanrolnik** [comment] 2017-10-26 08:56
@wesliel is correct. Please see the docs on `Parse.User.login()`: http://parseplatform.org/Parse-SDK-JS/api/classes/Parse.User.html#methods_logIn

Additionally, you are handling the error from the promise incorrectly. `Parse.Promise` differs from the other JS promise implementations:
http://parseplatform.org/Parse-SDK-JS/api/classes/Parse.Promise.html

**Comment by bouzoumita** [comment] 2017-10-27 12:17
i mean Parse.User.LogIn but it is typing fault, if i really test it with Parse.Login it will not execute it will through an error immediately and do not produce the output i'm showing.
And why you close the issue this does not resolve the first part it still log 404 not found.

**Comment by flovilmart** [comment] 2017-10-27 12:19
Are you passing the email and not the username?

**Comment by bouzoumita** [comment] 2017-10-27 12:21
the email is the username they are equal.

**Comment by flovilmart** [comment] 2017-10-27 12:32
Can you try with the latest version 1.10.1 and let us know if it’s the same?

**Comment by bouzoumita** [comment] 2017-10-27 13:02
I try 1.10.1 version with new projects using nextjs and using reactjs alone  but it still log that error 404 not found even when loging nothing.

**Comment by natanrolnik** [comment] 2017-10-27 13:19
@bouzoumita which parse-server version are you using? And when did this bug started happening?

**Comment by bouzoumita** [comment] 2017-10-27 13:40
i was using the version 2.6.3 of parse server, now I upgrade to 2.6.5 but still get same thing.

**Comment by natanrolnik** [comment] 2017-10-27 13:51
And if you try using the Rest API, do you get the same error? If so, then it’s a bug in Parse Server.

**Comment by flovilmart** [comment] 2017-10-27 13:55
@bouzoumita can you provide the server logs when running with VERBOSE=1 please?

**Comment by bouzoumita** [comment] 2017-10-27 14:22
@flovilmart  I dont know how to get the verbose log, it is hosted in the elastic beanstalk.
@natanrolnik the problem is visible only in the browser , with parse/node it run the error callback only

**Comment by artua** [comment] 2018-06-07 14:00
The same thing here.
Not working on 2.8.1, but working great with 2.7.2
Tried with REST API - the same error.
{"code":101,"error":"Invalid username/password."}

Let me know how can I help to resolve this issue.

**Comment by flovilmart** [comment] 2018-06-21 00:27
Are you able to open a PR with the failing test?

**Comment by fchu** [comment] 2018-06-21 01:13
Sorry, Ignore my comment, I could no longer repro 🤷‍♀️

**Closed** 2019-02-12 21:59 UTC
Labels: wontfix
