### ISSUE TITLE
Refused to get unsafe header "x-parse-job-status-id" (parse.min.js:13)

### ISSUE THREAD

**Issue by pargu** [parse-community/Parse-SDK-JS#622] opened 2018-08-06 12:54 UTC
We are getting this issue on one of our websites using Parse.Login function. It just happened suddenly, without any changes in code. 

Seems like there's another developer experiencing this also. Ref:
https://stackoverflow.com/questions/51706665/refused-to-get-unsafe-header-x-parse-job-status-id-angularjs-and-parse-serve/51707718#51707718 (1 h ago)

This only happens in the JavaScript SDK. Android and iOS logins are working normally...

Anyone have any insight how to fix this issue?

**Comment by flovilmart** [comment] 2018-08-06 13:18
We should add the access control expose headers in parse server in order to ‘fix’ this issue. You can ignore it for now.

**Comment by flovilmart** [comment] 2018-08-06 13:27
It shouldn’t, and the issue is in parse server and should be solved on parse server’s side. 

What version of the sevrer are you running?

**Comment by pargu** [comment] 2018-08-06 13:30
We're running 2.6.5 .. Have issues updating it to newer version. But that's another thing

**Comment by flovilmart** [comment] 2018-08-06 13:31
So even if I provide a fix, you won’t even be able to apply it.

**Comment by pargu** [comment] 2018-08-06 13:35
Probably. It's not a priority as of now, but something we have to do sooner or later

**Comment by pargu** [comment] 2018-08-06 14:14
Would you like to give some insight why this has started to happen as of now? And not before. Tried some diffrent browsers, and same issue everywhere.

**Comment by facchiR** [comment] 2018-08-06 14:15
Refused to get unsafe header "x-parse-job-status-id"
xhr.onreadystatechange @ parse.js:10727

i got this issue on almost every page on my website (stored in a web host)

I think the modification you did here (Check if job header is present #623) messed up application with older parse sdk. 
Could you check?

Everything was working few days ago..

**Comment by flovilmart** [comment] 2018-08-06 14:17
The fix on #623 is not merged yet and supposedly fixing the issue.

Can you try with it?

**Comment by facchiR** [comment] 2018-08-06 14:26
We are using Parse Server 2.6.5, we did not update to the new server yet.
Everything was working correctly last week, now i got an error on this source code:
if (typeof xhr.getResponseHeader === 'function') {
              var jobStatusId = xhr.getResponseHeader('x-parse-job-status-id'); <==== Bug here
              if (jobStatusId) {
                response = jobStatusId;
              }
            }

**Comment by flovilmart** [comment] 2018-08-06 14:26
I believe you're using the unpkg version:

https://unpkg.com/parse/dist/parse.js, and the minified production version is at https://unpkg.com/parse/dist/parse.min.js.

Which is automatically pointing to the latest release, you should use:

 https://unpkg.com/parse@1.11.1/dist/parse.js

**Comment by pargu** [comment] 2018-08-06 14:27
Same here. Haven't modified Client nor Server version

**Closed by flovilmart** 2018-08-06 14:26 UTC

**Comment by flovilmart** [comment] 2018-08-06 14:29
@pargu please, pin the SDK version to 1.11.1 as I mentioned just above. You guys are using the latest SDK version which contains this issue.

**Comment by facchiR** [comment] 2018-08-06 14:37
Everything it's working again for me! Thanks

**Comment by pargu** [comment] 2018-08-06 14:45
Working for us too 👍 Thank you @flovilmart

**Comment by patkozlowski** [comment] 2018-09-05 19:55
Thanks for the answer. Been scratching my head on this for a few days!
