### ISSUE TITLE
RN 0.50.1 StorageController.react-native.js Break 

### ISSUE THREAD

**Issue by BenBenz** [parse-community/Parse-SDK-JS#508] opened 2017-11-16 18:47 UTC
I've setup a new project with Parse, Mobx etc...

But I can't use Parse because I have this error 

bundling failed: UnableToResolveError: Unable to resolve module `react-native/Libraries/react-native/react-native.js` from `LONGPATH/node_modules/parse/lib/react-native/StorageController.react-native.js`: Module does not exist in the module map

I've solve the problem when I have change this:
```
try {
	// for React Native 0.43+
	AsyncStorage = require('react-native/Libraries/react-native/react-native-implementation')
		.AsyncStorage;
} catch (error) {
	AsyncStorage = require('react-native/Libraries/react-native/react-native.js').AsyncStorage;
}

```

to this

```
try {
	// for React Native 0.43+
	AsyncStorage = require('react-native/Libraries/react-native/react-native-implementation')
		.AsyncStorage;
} catch (error) {
	// AsyncStorage = require('react-native/Libraries/react-native/react-native.js').AsyncStorage;
}
```

I've try to debug and my the application don't go to the catch but it break the code ...

I use react native 50.1

**Comment by mcwebb** [comment] 2017-11-17 08:37
Duplicate of #496.

**Closed** 2017-12-02 19:14 UTC
