### ISSUE TITLE
Unexpected behaviour of Parse.Object.dirty(attr?: string): boolean

### ISSUE THREAD

**Issue by percypyan** [parse-community/Parse-SDK-JS#1079] opened 2020-02-06 11:30 UTC
### Issue Description

The explanation concerning `Parse.Object.dirty(attr?: string): boolean` is the following:
```
   * Returns true if this object has been modified since its last
   * save/refresh.  If an attribute is specified, it returns true only if that
   * particular attribute has been modified since the last save/refresh.
```

This implies that:
```
const obj = new TestObject()
obj.set("aKey", "aValue")
obj.dirty() // true
obj.dirty("aKey") // true
obj.dirty("anAttributeName") // false
obj.dirtyKeys() // ["aKey"]
```
Every thing work fine, EXCEPT for the line `obj.dirty("anAttributeName") // false`.
For this call, `dirty` returns `true`, even if the key "anAttributeName" has not been modified since the last save/refresh.

### Steps to reproduce

```
const obj = new TestObject()
obj.set("aKey", "aValue")
obj.dirty() // true
obj.dirty("aKey") // true
obj.dirty("anAttributeName") // true <= the bug is here
obj.dirtyKeys() // ["aKey"]
```

### Expected Results

```
obj.dirty("anAttributeName") // false
```

### Actual Outcome

```
obj.dirty("anAttributeName") // true
```

### Test Case

To accurately reproduce your issue. Add your test cases [here](https://github.com/parse-community/Parse-SDK-JS/tree/master/integration/test) and read the [Contributing Guide](https://github.com/parse-community/Parse-SDK-JS/blob/master/CONTRIBUTING.md) to run the tests. 

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.10
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Localhost, Heroku

- **JS SDK**
  - JS SDK version: 2.11
  - Application? (Browser, Node, React-Native, etc): Node

### Logs/Trace

None.

### Guilty code

l.476 to l.486 in src/ParseObject.js
https://github.com/parse-community/Parse-SDK-JS/blob/0dc0ee59e2efe3bd4b917936551979171c4551f0/src/ParseObject.js#L484

```
  /**
   * Returns true if this object has been modified since its last
   * save/refresh.  If an attribute is specified, it returns true only if that
   * particular attribute has been modified since the last save/refresh.
   * @param {String} attr An attribute name (optional).
   * @return {Boolean}
   */
  dirty(attr?: string): boolean {
    if (!this.id) {
      return true;
    }
```

This should be:
```
    if (!attr && !this.id) {
      return true;
    }
```
instead.

I'll do a PR if you confirm me that's a bug @dplewis.

**Comment by davimacedo** [comment] 2020-02-07 01:03
Just to make sure, `anAttributeName` is an attribute that already exists in the schema, right?

**Comment by dplewis** [comment] 2020-02-07 01:14
It looks like a bug to me. I'll see if this exists in the other repos just to be sure.

**Comment by dplewis** [comment] 2020-02-07 03:00
> Returns true if this object has been modified since its last save/refresh

The key here is `last save/refresh`. unsaved are objects are always dirty. 

```
if (!this.id) { <-- Means unsaved object
  return true;
}
```

Closing as this is expected behaviors.

**Closed by dplewis** 2020-02-07 03:00 UTC
Labels: bug

**Comment by percypyan** [comment] 2020-02-07 08:28
Look at this: « If an attribute is specified, it return true only if that particuliar attribute has been modified since the last save/refresh. »

How an attribute that hasn’t been set can be dirty in that case? I’m understanding that the object it self is always dirty if it hasn’t been save. But this is non-sens to me to get true when an attribute (belonging to the schema) hasn’t been set yet on the object. In fact, the dirtyKeys method does not return the key, even if it’s belong to the schema. And this a logical way to evaluates the dirty state of a key.

.dirty(attribute) should always returns the same as .dirtyKeys().includes(attribute) I think.

Even if .dirty() should return true for unsaved object.

**Comment by dplewis** [comment] 2020-02-07 11:34
That would be true but the SDKs don’t know anything about the schema that lives in a DB somewhere. You simple create an object and send it to the server.

**Comment by percypyan** [comment] 2020-02-10 10:24
Ok, but in this case you should rephrase this description since it's erroneous. 
`If an attribute is specified, it return true only if that particuliar attribute has been modified since the last save/refresh.`
Should be `If the object isn't new and an attribute is specified, it return true only if that particuliar attribute has been modified since the last save/refresh.`.
I've never modified "anAttributeName" in my exemple: it can't be dirty. This object is but it's not the information I want to get since I specified an attribute.

It's not especially problematic that the behaviour of `.dirty(attr)` do not match `.dirtyKeys().includes(attr)`, but it should be clear in the description.

This was not the behaviour I was expecting when I rely on `.dirty` to run some checks on a specific attribute if it was set or update since the last save or before the first one.
In my case I've replace my check for dirty state by `.dirtyKeys().includes(attr)`.
