### ISSUE TITLE
Parse.Object.fromJSON creates empty record in DB

### ISSUE THREAD

**Issue by andrekosak** [parse-community/Parse-SDK-JS#482] opened 2017-09-19 09:56 UTC
SDK package version: **1.10.0**

When I use Parse.Object.fromJSON on NodeJS server, record are being created containing only `objectId`, `createdAt`, `updatedAt`. All other properties i have passed in my JSON are being ignored.

In the example below I am trying to create an object with properties `a` and `b`, but they are not being passed to server. At first I create an object and then getting this object by its ID to see if it has my properties.

Here is my code:

```
const testObject = {
    a: 1,
    b: 2,
    className: 'TestOnly1'
}
const test = Parse.Object.fromJSON(testObject);
test.save()
    .then((newObject) => {
        console.log(JSON.stringify(newObject, null, 3));

        const query = new Parse.Query('TestOnly1')
        query.get(newObject.id)
            .then((queryResponse) => {
                console.log(JSON.stringify(queryResponse, null, 3));
            })
    });
```
console output from first console.log():

```
{
   "a": 1,
   "b": 2,
   "createdAt": "2017-09-19T09:48:58.174Z",
   "updatedAt": "2017-09-19T09:48:58.174Z",
   "objectId": "fqJV15MOLK"
}
```

output from second console.log():

```
{
   "createdAt": "2017-09-19T09:48:58.174Z",
   "updatedAt": "2017-09-19T09:48:58.174Z",
   "objectId": "fqJV15MOLK"
}
```

Is it a bug or i am doing something wrong?

**Comment by dplewis** [comment] 2018-03-11 00:49
I saw this as well. Look like `fromJSON` wasn't designed to save data.

* `save` only works on dirty fields i.e `obj.set()` that have yet to be committed and not in the cache.
* `fromJSON` saves fields in the cache.
* Your example ends up with no dirty fields to be saved since all the data is cache.
* `save.then(newObject)` just returning what was in the cache

@flovilmart Is this by design or for offline use?

**Comment by flovilmart** [comment] 2018-03-11 00:51
I’m not sure, i’ll Have to investigate more, starting with when it was added :)

**Closed** 2019-02-13 06:00 UTC
Labels: wontfix

**Comment by francojohnc** [comment] 2020-10-20 11:35
I check the code and no set called from parse object


```
static fromJSON(json
  /*: any*/
  , override
  /*:: ?: boolean*/
  ) {
    if (!json.className) {
      throw new Error('Cannot create an object without a className');
    }

    const constructor = classMap[json.className];
    const o = constructor ? new constructor() : new ParseObject(json.className);
    const otherAttributes = {};

    for (const attr in json) {
      if (attr !== 'className' && attr !== '__type') {
        otherAttributes[attr] = json[attr];
      }
    }

    if (override) {
      // id needs to be set before clearServerData can work
      if (otherAttributes.objectId) {
        o.id = otherAttributes.objectId;
      }

      let preserved = null;

      if (typeof o._preserveFieldsOnFetch === 'function') {
        preserved = o._preserveFieldsOnFetch();
      }

      o._clearServerData();

      if (preserved) {
        o._finishFetch(preserved);
      }
    }

    o._finishFetch(otherAttributes);

    if (json.objectId) {
      o._setExisted(true);
    }

    return o;
  }

```
